spring:
  application:
    name: tanzu-java-web-app
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always
greeting: "TAP workload/SCC basic - Jul07 - 11:42"